//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wp7AzureMgmt.DashboardFeeds.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSSFeedResponseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSSFeedResponseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wp7AzureMgmt.DashboardFeeds.Test.RSSFeedResponseResource", typeof(RSSFeedResponseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                    &lt;td&gt;
        ///                        &lt;span id=&quot;ctl00_MainContent_lblPageLastUpdated&quot;&gt;Page Last Updated:   6 Apr 2012 11:08 PM UTC&lt;/span&gt;
        ///                    &lt;/td&gt;
        ///                .
        /// </summary>
        internal static string TestFail2 {
            get {
                return ResourceManager.GetString("TestFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///                        &lt;span id=&quot;ctl00_MainContent_lblPageLastUpdated&quot;&gt;Page Last Updated:   6 Apr 2012 11:08 PM UTC&lt;/span&gt;
        ///                    &lt;/td&gt;.
        /// </summary>
        internal static string TestTDFail1 {
            get {
                return ResourceManager.GetString("TestTDFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             &lt;div class=&quot;centerAlign&quot;&gt;
        ///                                &lt;a id=&quot;ctl00_MainContent_gvStatusToday_ctl30_hyperlinkRSS&quot; href=&quot;RSSFeed.aspx?RSSFeedCode=DSSSCU&quot; target=&quot;_parent&quot;&gt;&lt;img src=&quot;Images/Rss_New.png&quot; border=&quot;0&quot; /&gt;&lt;/a&gt;&lt;/div&gt;.
        /// </summary>
        internal static string TestTDSuccess_cellStyleTodayDetails {
            get {
                return ResourceManager.GetString("TestTDSuccess_cellStyleTodayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;leftAlign&quot;&gt;
        ///                                &lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl30_lblServiceName&quot;&gt;SQL Azure Data Sync&lt;/span&gt;
        ///                                [&lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl30_lblRegionName&quot;&gt;South Central US&lt;/span&gt;]
        ///                            &lt;/div&gt;
        ///                                &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$gvStatusToday$ctl30$hdnServiceId&quot; id=&quot;ctl00_MainContent_gvStatusToday_ctl30_hdnServiceId&quot; value=&quot;17&quot; /&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTDSuccess_cellStyleTodayService {
            get {
                return ResourceManager.GetString("TestTDSuccess_cellStyleTodayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;th class=&quot;headerStyleTodayStatus&quot; scope=&quot;col&quot;&gt;
        ///                            &lt;div class=&quot;centerAlign&quot;&gt;
        ///                                &lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl01_lblStatus&quot;&gt;Status&lt;/span&gt;
        ///                            &lt;/div&gt;
        ///                        &lt;/th&gt;&lt;th class=&quot;headerStyleTodayService&quot; scope=&quot;col&quot;&gt;
        ///                            &lt;div class=&quot;leftAlign&quot;&gt;
        ///                                &lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl01_lblService&quot;&gt;Service [Sub-Region]&lt;/span&gt;&lt;/div&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTRFail1 {
            get {
                return ResourceManager.GetString("TestTRFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;td class=&quot;cellStyleTodayStatus&quot;&gt;
        ///                            &lt;div class=&quot;centerAlign&quot;&gt;
        ///                                &lt;img id=&quot;ctl00_MainContent_gvStatusToday_ctl03_imgStatus&quot; src=&quot;/windowsazure/support/status/Images/green.png&quot; border=&quot;0&quot; /&gt;
        ///                            &lt;/div&gt;
        ///                            
        ///                            &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$gvStatusToday$ctl03$hdnStatusColor&quot; id=&quot;ctl00_MainContent_gvStatusToday_ctl03_hdnStatusColor&quot; value=&quot;Green&quot; /&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTRSuccess1 {
            get {
                return ResourceManager.GetString("TestTRSuccess1", resourceCulture);
            }
        }
    }
}
