//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wp7AzureMgmt.DashboardFeeds.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSSFeedResponseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSSFeedResponseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wp7AzureMgmt.DashboardFeeds.Test.RSSFeedResponseResource", typeof(RSSFeedResponseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                &lt;span id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_lblServiceName_0&quot;&gt;Access Control 1.0&lt;/span&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems1 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_lblRegionName_0&quot;&gt;East Asia&lt;/span&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems2 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$tcStatus$tpAllStatusToday$gvAllStatusToday$ctl02$hdnServiceId&quot; id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hdnServiceId_0&quot; value=&quot;6&quot; /&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems3 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$tcStatus$tpAllStatusToday$gvAllStatusToday$ctl02$hdnRegionId&quot; id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hdnRegionId_0&quot; value=&quot;7&quot; /&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems4 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$tcStatus$tpAllStatusToday$gvAllStatusToday$ctl02$hdnRSSFeedCode&quot; id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hdnRSSFeedCode_0&quot; value=&quot;NSACSEA&quot; /&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems5 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hyperlinkRSS_0&quot; href=&quot;RSSFeed.aspx?RSSFeedCode=NSACSEA&quot; target=&quot;_parent&quot;&gt;&lt;img src=&quot;Images/Rss_New.png&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;.
        /// </summary>
        internal static string ParseFeedNodeItems6 {
            get {
                return ResourceManager.GetString("ParseFeedNodeItems6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                    &lt;td&gt;
        ///                        &lt;span id=&quot;ctl00_MainContent_lblPageLastUpdated&quot;&gt;Page Last Updated:   6 Apr 2012 11:08 PM UTC&lt;/span&gt;
        ///                    &lt;/td&gt;
        ///                .
        /// </summary>
        internal static string TestFail2 {
            get {
                return ResourceManager.GetString("TestFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///                        &lt;span id=&quot;ctl00_MainContent_lblPageLastUpdated&quot;&gt;Page Last Updated:   6 Apr 2012 11:08 PM UTC&lt;/span&gt;
        ///                    &lt;/td&gt;.
        /// </summary>
        internal static string TestTDFail1 {
            get {
                return ResourceManager.GetString("TestTDFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_imgStatus_0&quot; src=&quot;/windowsazure/support/status/Images/green.png&quot; /&gt;
        ///                            
        ///                            &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$tcStatus$tpAllStatusToday$gvAllStatusToday$ctl02$hdnStatusColor&quot; id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hdnStatusColor_0&quot; value=&quot;Green&quot; /&gt;
        ///                        &lt;/td&gt;&lt;td class=&quot;currentStatusService&quot;&gt;
        ///                                &lt;span id=&quot;MainConten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTDSuccess_cellStyleTodayService {
            get {
                return ResourceManager.GetString("TestTDSuccess_cellStyleTodayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;th class=&quot;headerStyleTodayStatus&quot; scope=&quot;col&quot;&gt;
        ///                            &lt;div class=&quot;centerAlign&quot;&gt;
        ///                                &lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl01_lblStatus&quot;&gt;Status&lt;/span&gt;
        ///                            &lt;/div&gt;
        ///                        &lt;/th&gt;&lt;th class=&quot;headerStyleTodayService&quot; scope=&quot;col&quot;&gt;
        ///                            &lt;div class=&quot;leftAlign&quot;&gt;
        ///                                &lt;span id=&quot;ctl00_MainContent_gvStatusToday_ctl01_lblService&quot;&gt;Service [Sub-Region]&lt;/span&gt;&lt;/div&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTRFail1 {
            get {
                return ResourceManager.GetString("TestTRFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;currentStatusStatus&quot;&gt;
        ///                                &lt;img id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_imgStatus_0&quot; src=&quot;/windowsazure/support/status/Images/green.png&quot; /&gt;
        ///                            
        ///                            &lt;input type=&quot;hidden&quot; name=&quot;ctl00$MainContent$tcStatus$tpAllStatusToday$gvAllStatusToday$ctl02$hdnStatusColor&quot; id=&quot;MainContent_tcStatus_tpAllStatusToday_gvAllStatusToday_hdnStatusColor_0&quot; value=&quot;Green&quot; /&gt;
        ///                        &lt;/td&gt;&lt;td class=&quot;currentSta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTRSuccess1 {
            get {
                return ResourceManager.GetString("TestTRSuccess1", resourceCulture);
            }
        }
    }
}
