//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wp7AzureMgmt.DashboardFeeds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wp7AzureMgmt.DashboardFeeds.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HtmlTest {
            get {
                return ResourceManager.GetString("HtmlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;http://www.microsoft.com/feeds/msdn_opmlpretty.xsl&quot; version=&quot;1.0&quot;?&gt;
        ///&lt;opml version=&quot;1.1&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Azure Service Dashboard Feeds&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///$$content 
        ///  &lt;/body&gt;
        ///&lt;/opml&gt;
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;.
        /// </summary>
        internal static string OPMLMaster {
            get {
                return ResourceManager.GetString("OPMLMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;outline text=&quot;$$name [$$location]&quot; title=&quot;$$name [$$location]&quot; type=&quot;rss&quot; xmlUrl=&quot;http://www.microsoft.com/windowsazure/support/status/RSSFeed.aspx?RSSFeedCode=$$code&quot; htmlUrl=&quot;http://www.microsoft.com/windowsazure/support/status/servicedashboard.aspx&quot;/&gt;.
        /// </summary>
        internal static string OPMLMasterOutline {
            get {
                return ResourceManager.GetString("OPMLMasterOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;http://www.microsoft.com/feeds/msdn_opmlpretty.xsl&quot; version=&quot;1.0&quot;?&gt;
        ///&lt;opml version=&quot;1.1&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Azure Service Dashboard Feeds&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///&lt;outline text=&quot;Access Control [East Asia]&quot; title=&quot;Access Control [East Asia]&quot; type=&quot;rss&quot; xmlUrl=&quot;http://www.microsoft.com/windowsazure/support/status/RSSFeed.aspx?RSSFeedCode=NSACSEA&quot; htmlUrl=&quot;http://www.microsoft.com/windowsazure/support/status/servicedashboard.aspx&quot;/&gt;&lt;outline text=&quot;Service Bus [Sou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPMLTest {
            get {
                return ResourceManager.GetString("OPMLTest", resourceCulture);
            }
        }
    }
}
